version: '3.8'
services:
  key-clock:
    container_name: "key-clock"
    image: "quay.io/keycloak/keycloak:24.0.2"
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
      - "start-dev"
      - "--import-realm"