micronaut:
  security:
    authentication: cookie
    oauth2:
      clients:
        demo:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'localhost:8180/realms/master'
